#!/bin/bash

COMMIT_MSG_FILE=$1

# Check subject rule
subjectLine=$(head $COMMIT_MSG_FILE | grep -m 1 "^[^#]")
echo $subjectLine
if [ ${subjectLine%% *} = Merge ]; then
    exit 0
fi

tpe=$(sed "s/^\[\([^]]*\)\].*/\1/g" <<< $subjectLine)
sbj=$(sed "s/^[^ ]* //" <<< $subjectLine)

if ! [[ $tpe =~ ^(feat|fix|refactor|style|docs|test|chore)$ ]]; then
    echo >&2 "[*] Unknown type used"
    exit 1
fi

if [[ ! ${sbj:0:1} =~ [A-Z] ]] || [[ ${sub: -1} = "." ]]; then
    echo >&2 "[*] Not correctly formatted subject"
    exit 1
fi

# Check line length of body
bodyLines=$(sed -n '4,$p' $COMMIT_MSG_FILE | grep '^[^#]')

for l in $bodyLines
do
    if [[ ${#l} -gt 72 ]]; then
        echo >&2 "[*] Too long body lines"
        exit 1
    fi
done

# Check Signed-off-by at last 
lastLine=$(tac $COMMIT_MSG_FILE | egrep -m 1 "^[^#]")

if [[ $lastLine != Signed-off-by:*  ]]; then
    echo >&2 "[*] Not ending with Signed-off-by line"
    exit 1
fi
